### ISSUE TITLE
ReadMe Proofreading

### ISSUE THREAD

**Issue by rayliverified** [escamoteur/get_it_mixin#1]
Starting a proofreading thread to consolidate errors and suggestions for improvements.

**Comment by rayliverified** [comment]
![MaxthonSnap20201003143124](https://user-images.githubusercontent.com/19896174/95000297-3f8e1f00-0585-11eb-91b8-5c52162b0980.png)

**Comment by rayliverified** [comment]
Confusing sentence because what does "all of these function" refer to?
![MaxthonSnap20201003143421](https://user-images.githubusercontent.com/19896174/95000349-ab708780-0585-11eb-912b-aa2631d4f024.png)

**Comment by rayliverified** [comment]
Typo
![MaxthonSnap20201003144404](https://user-images.githubusercontent.com/19896174/95000495-e7f0b300-0586-11eb-9e6e-187c10c673d4.png)

**Comment by rayliverified** [comment]
Typo
![MaxthonSnap20201003164015](https://user-images.githubusercontent.com/19896174/95002218-22fae280-0597-11eb-9512-ae34e2077d52.png)

**Comment by escamoteur** [comment]
> Confusing sentence because what does "all of these function" refer to?
> ![MaxthonSnap20201003143421](https://user-images.githubusercontent.com/19896174/95000349-ab708780-0585-11eb-912b-aa2631d4f024.png)

I meant the following functions.

Do you want to make a PR with the fixes?

**Comment by rayliverified** [comment]
Will do! I'll open a PR and let it collect the proofreading changes for you to merge at your convenience.

**Comment by rayliverified** [comment]
The two variable names should match or an explanation should be added to explain what the instance name does?

![MaxthonSnap20201011210944](https://user-images.githubusercontent.com/19896174/95697984-2aa92f80-0c06-11eb-96ec-b899786197af.png)

**Comment by escamoteur** [comment]
Could you make a PR so that I don't have to got and search and update the Readme. would be great. If you haven't done a PR before I can help you if you want.
