### ISSUE TITLE
Error using pushScope

### ISSUE THREAD

**Issue by chimon2000** [escamoteur/get_it_mixin#15]
I have a new page that initializes its dependency in the build method like so:

```dart
  Widget build(BuildContext context) {
    pushScope(
        init: (locator) => locator.registerSingleton(PreferencesViewModel()));

    return Scaffold(
      body: SafeArea(child: _buildContent(context)),
    );
  }
```

I get the following exception after popping the page:

```bash
Another exception was thrown: You already have used the scope name null

I/flutter (14985): 'package:get_it/get_it_impl.dart':
I/flutter (14985): Failed assertion: line 732 pos 7: '_scopes.firstWhereOrNull((x) => x.name == scopeName) == null'
I/flutter (14985): 
I/flutter (14985): The relevant error-causing widget was:
I/flutter (14985):   PreferencesPage
I/flutter (14985):   file:///hello_world/app/preferences_page.dart:14:56
I/flutter (14985): 
I/flutter (14985): When the exception was thrown, this was the stack:
I/flutter (14985): #2      _GetItImplementation.pushNewScope (package:get_it/get_it_impl.dart:732:7)
I/flutter (14985): #3      _MixinState.pushScope (package:get_it_mixin/src/mixin_state.dart:540:15)
I/flutter (14985): #4      GetItMixin.pushScope (package:get_it_mixin/src/mixin.dart:240:20)
I/flutter (14985): #5      PreferencesPage.build (package:serqit_app/ui/preferences/preferences_page.dart:18:5)
I/flutter (14985): #6      StatelessElement.build (package:flutter/src/widgets/framework.dart:4648:28)
I/flutter (14985): #7      _GetItElement.build (package:get_it_mixin/src/elements.dart:16:18)
I/flutter (14985): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
I/flutter (14985): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (14985): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
I/flutter (14985): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
I/flutter (14985): #12     _GetItElement.mount (package:get_it_mixin/src/elements.dart:9:11)
```

I am not sure what I am doing wrong if anything.

**Comment by escamoteur** [comment]
Hi Ryan, you are doing nothing wrong I think, but it would help me to make the fix correctly if I could know some more information.

1. you say it happens after you pop the page. Does the page below also push a scope? Because it clearly happens in a pushScope call.
2. have you pushed anywhere else in the app a scope without name? I probably should just remove this assert if no name was provided but I want to be sure.

**Comment by chimon2000** [comment]
> 1. you say it happens after you pop the page. Does the page below also push a scope? Because it clearly happens in a pushScope call.

The build method of `PreferencesPage` pushes the  `PreferencesViewModel` so a new push occurs whenever navigating to the page.  

> 2. have you pushed anywhere else in the app a scope without name? I probably should just remove this assert if no name was provided but I want to be sure.

This is the only instance that I am using `pushScope` in the application.

**Comment by escamoteur** [comment]
But you say the exception is thrown when you pop the PreferencePage? Because how does it reach the PushScope call while popping?

**Comment by escamoteur** [comment]
actually thinking a bit more about this I might be a good idea to give scopes that are pushed by the mixin a unique name and do a popUntil when the Widget is destroyed in case some code after that pushScope does anoher push manually.
What do you think?

On the other side you probably shouldn't mix manual scoping and automatic one

**Comment by escamoteur** [comment]
finally implemented in the latest version :-)
