### ISSUE TITLE
WatchStream Exception When Handling AsyncSnapshot<Type> Instead of Type

### ISSUE THREAD

**Issue by rayliverified** [escamoteur/get_it_mixin#2]
`watchStream` might be broken because it tries to return a AsyncSnapshot<Type> instead of the <Type>

I am trying to watch the Firebase Auth. 
`final User user = watchStream((AuthService auth) => auth.user, null).data;`

The Stream in `AuthService` is 
`Stream<User> get user => _auth.authStateChanges();`

The following error is thrown: 
`type 'AsyncSnapshot<User>' is not a subtype of type 'User'`

Error location: 

> Dart Unhandled Exception: type 'AsyncSnapshot<User>' is not a subtype of type 'User' of 'value', stack trace: #0      _WatchEntry.lastValue= (package:get_it_mixin/src/mix_in.dart)
 _MixinState.watchStream.<anonymous closure> (package:get_it_mixin/src/mix_in.dart:793:15)

**Comment by rayliverified** [comment]
![MaxthonSnap20201011221424](https://user-images.githubusercontent.com/19896174/95701413-26354480-0c0f-11eb-97d5-0cb40ae7493f.png)

**Comment by escamoteur** [comment]
No, that's the corrrect behaviour as an async snapshot contains more information than just the data. In case of an error it contains the error. And it contains the current connection state.

**Comment by rayliverified** [comment]
Will add test project to demo that there is an internal error that throws the exception.

**Comment by rayliverified** [comment]
This error looks to be Firebase specific. 

For some reason, Firebase returns an AsyncSnapshot from the Stream instead of a User.
`Stream<User> get user => _auth.authStateChanges();`

![MaxthonSnap20201012154445](https://user-images.githubusercontent.com/19896174/95788824-e5d2d680-0ca1-11eb-96f2-64ed6b07a2df.png)


<details><summary>Firebase Code</summary>

```dart
import 'dart:async';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:get_it_mixin/get_it_mixin.dart';

class GetItStreamTypeIssueModel extends ChangeNotifier {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  Stream<User> get user => _auth.authStateChanges();
}

final GetIt g = GetIt.instance;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  registerViewModel();
  runApp(MyApp());
}

void registerViewModel() {
  g.registerSingleton<GetItStreamTypeIssueModel>(GetItStreamTypeIssueModel());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'GetIt Stream Type Issues',
      home: Scaffold(body: SafeArea(child: StreamTypeIssue())),
    );
  }
}

class StreamTypeIssue extends StatefulWidget with GetItStatefulWidgetMixin {
  @override
  _StreamTypeIssueState createState() => _StreamTypeIssueState();
}

class _StreamTypeIssueState extends State<StreamTypeIssue>
    with GetItStateMixin {
  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    watchStream((GetItStreamTypeIssueModel model) => model.user, null);
    return Column(
      children: [
        Text('Type Name: '),
      ],
    );
  }
}
```

</details>

**Comment by escamoteur** [comment]
Ah, now I get it. you mean the x is already an AsyncSnapshot and I try to wrap it in another snapshot?
Could you show me the part were you get your Stream from firebase?

**Comment by rayliverified** [comment]
Thanks for the quick reply.

![MaxthonSnap20201012155140](https://user-images.githubusercontent.com/19896174/95789276-da33df80-0ca2-11eb-94ca-20dedf341d56.png)

**Comment by escamoteur** [comment]
hmm, strange. could you do me a favor and try if the same thing happens if you use get_it_hooks instead of the mixin. It is implemented a bit different and would help me getting a better idea. I would have to setup a firebase auth which I can do tomorrow. I wonder why the stream tests worked

**Comment by rayliverified** [comment]
I can try tomorrow. 

Thanks for offering to setup firebase_auth. I was unable to replicate their implementation because it looks like the type safety doesn't work because they are passing back the result from a platform channel. Could be totally off base there.

**Comment by escamoteur** [comment]
I tried it and it works without problems.

```Dart
class AuthManager {
  Stream<User> _userStream;
  Stream<User> get userUpdates {
    if (_userStream == null) {
      _userStream = FirebaseAuth.instance.authStateChanges();
    }

    /// I don't want the getter to produce a new stream on every call;
    return _userStream;
  }
```

```Dart
  Widget build(BuildContext context) {
    final user = watchStream((AuthManager a) => a.userUpdates, null);
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'User s',
            ),
            Text(
              user?.data?.email ?? 'No user',
              style: Theme.of(context).textTheme.headline4,
            ),
            FloatingActionButton(
              child: Text('-'),
              onPressed: () async => await FirebaseAuth.instance.signOut(),
            )
          ],
        ),
```

**Comment by rayliverified** [comment]
Thank you for testing. Let me test with your code. 
The problem is most likely my implementation which is good news.

**Comment by rayliverified** [comment]
There was the multiple listener issue that you fixed in v1.5.1 but it is still popping up with watchStream I believe. It is fixed with watch but not watchStream.

Please try running the following code in Flutter web and you will see a max call stack size exceeded error.

<details><summary>Firebase Auth Code</summary>

```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:get_it_mixin/get_it_mixin.dart';

final GetIt g = GetIt.instance;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  initManagers();
  runApp(MyApp());
}

void initManagers() {
  g.registerSingleton<AuthManager>(AuthManager());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Test',
      home: Scaffold(body: SafeArea(child: FirebaseTest())),
    );
  }
}

class FirebaseTest extends StatefulWidget with GetItStatefulWidgetMixin {
  @override
  _FirebaseTestState createState() => _FirebaseTestState();
}

class _FirebaseTestState extends State<FirebaseTest> with GetItStateMixin {
  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final user = watchStream((AuthManager a) => a.userUpdates, null);
    return Column(
      children: [],
    );
  }
}

class AuthManager {
  Stream<User> _userStream;

  Stream<User> get userUpdates {
    if (_userStream == null) {
      _userStream = FirebaseAuth.instance.authStateChanges();
    }

    return _userStream;
  }
}
```
</details>

**Comment by escamoteur** [comment]
I just ran my example app which is almost the same on web without any problems.

**Comment by rayliverified** [comment]
Thanks, let me test again tomorrow with a new project and hopefully close this issue.

**Comment by escamoteur** [comment]
Did it work?

**Comment by rayliverified** [comment]
Hi Thomas, sorry for the delay in responding.

I switched to a new computer but am still running into an issue.

Whenever I run the code with the GetItMixin more than once in the web browser, it throws a `maximum call stack exceeded` error.

![MaxthonSnap20201027220811](https://user-images.githubusercontent.com/19896174/97386020-f178ec80-18a0-11eb-8967-699de6ae566c.png)

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
Invalid argument: Maximum call stack size exceeded
The relevant error-causing widget was: 
  SafeArea file:///F:/Development/FlutterCoffeeCalendar/lib/main_firebase_auth_test.dart:26:28
════════════════════════════════════════════════════════════════════════════════════════════════════
```

I switched computers and redownloaded my entire dev environment. 

Can you try running the code below using the latest `beta` branch? 

<summary>Firebase Auth Code</summary><details>

```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:get_it_mixin/get_it_mixin.dart';

final GetIt g = GetIt.instance;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  initManagers();
  runApp(MyApp());
}

void initManagers() {
  g.registerSingleton<AuthManager>(AuthManager());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Test',
      home: Scaffold(body: SafeArea(child: FirebaseTest())),
    );
  }
}

class FirebaseTest extends StatefulWidget with GetItStatefulWidgetMixin {
  @override
  _FirebaseTestState createState() => _FirebaseTestState();
}

class _FirebaseTestState extends State<FirebaseTest> with GetItStateMixin {
  @override
  void initState() {
    super.initState();
    FirebaseAuth.instance.signInAnonymously();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final user = watchStream((AuthManager a) => a.userUpdates, null);
    return Column(
      children: [],
    );
  }
}

class AuthManager {
  Stream<User> _userStream;

  Stream<User> get userUpdates {
    if (_userStream == null) {
      _userStream = FirebaseAuth.instance.authStateChanges();
    }

    return _userStream;
  }
}
```

</details>

If everything works on your end, then let's chalk this up to something wrong with my system and close the issue.

**Comment by escamoteur** [comment]
What do you mean by running more than onces?

**Comment by rayliverified** [comment]
If I press play to launch the code, anytime I rerun either via hot reload or close and press play again, it will throw the error. 
The only way to get rid of the error is to close Android Studio. 
Then, it only works once before getting the error again.

**Comment by escamoteur** [comment]
A, thanks. Have you tried if it happens with vs code too?Also have you tried it with my Firebase test project too? Am 28.10.2020 14:53 schrieb Ray Li <notifications@github.com>:
If I press play to launch the code, anytime I rerun either via hot reload or close and press play again, it will throw the error.
The only way to get rid of the error is to close Android Studio.
Then, it only works once before getting the error again.

**Comment by rayliverified** [comment]
I have not tried with VS Code. 
Just tested with your code and I run into the same issue.
![MaxthonSnap20201029112633](https://user-images.githubusercontent.com/19896174/97602751-ac0c0a80-19d9-11eb-8953-eae4e4948555.png)

**Comment by rayliverified** [comment]
I am open to scheduling a meeting if you think that would help.

**Comment by escamoteur** [comment]
I'm just trying to reproduce it

**Comment by escamoteur** [comment]
Just tried it with latest master. I add you to my sample project

**Comment by escamoteur** [comment]
I will try with beta now. Btw are you in the Flutter Studygroup Slack?

**Comment by escamoteur** [comment]
I can reproduce on latest beta

**Comment by escamoteur** [comment]
I tried again with master and it works.

**Comment by rayliverified** [comment]
Great, thank you for your investigation!

**Comment by rayliverified** [comment]
I am not in the Flutter Studygroup
