### ISSUE TITLE
Using the watch calls on specific GetIt instance?

### ISSUE THREAD

**Issue by janmiderback** [escamoteur/get_it_mixin#25]
This is not a bug report, rather a request or a question on how to achieve a certain setup.

I would like to use `get_it_mixin` in a way that makes it possible that each instance of a widget has its own "view model" (state), backed by `get_it_mixin`.

So when my widget gets created, my view model object should be created in a one-to-one mapping. Here is where I run into problems registering them as singletons with the global `GetIt`, since it would give me the same view model instance each time.

I have experimented with `pushScope` but I'm not sure if that is the correct path.

The other idea is that my widget creates it own `GetIt`-instance but then the `watch` calls all work with the global `GetIt` instance, so that breaks.

Any ideas on how to do this? Also, am I doing something that seems completely wrong?
Any advice appreciated. Cheers!

[EDIT]
[The same problem formulation and a solution with Riverpod](https://stackoverflow.com/questions/67091556/flutter-riverpod-how-to-create-different-instances-of-the-same-provider-for-eac)

**Comment by escamoteur** [comment]
Hi. I'm reall sorry to see this so late.
I personally prefer longer lived business objects called Managers, that server not one but multiple Widgets with a similar topic.
One way you could go is register multiple instances of your ViewModels using the optional `instanceName` to differentiate between the viewmodels.
Scopes should be used to achieve different behavior in different app states, like logged in/out

**Comment by kevlar700** [comment]
Do you use stateful widgets and setState a fair amount. I have seen truly global code like get_it bluetooth managers but many riverpod users push stateless widgets even for local ui state and not just business logic. I guess if you have a fade in boolean or state property on 100 pages then you use pushscope on each or would you use a stateful widget?

**Comment by escamoteur** [comment]
Hmm, have you tried using different instance names when registering view models?
Also check out the successor of the get_it_mixin : watch_it, this indeed allows to use different get_it instances. However I m not sure that you are on the right way with your approach.

Thomas
Am 7. Feb. 2023, 17:40 +0100 schrieb Jan Miderbäck ***@***.***>:

**Comment by esDotDev** [comment]
Pretty sure the most robust flow here is
```dart
class MyWidgetState extends State {
  void initState(){
     // push scope
     // register singleton
  }

  void dispose(){
    // pop scope
  }
}
```
Fundamentally GetIt is a ServiceLocator package for Singletons, it's designed to ease the use of shared global objects, not really optimized for per-view single-use objects. I think that is why it's a bit clunky to use here. 

With that said, if this is a common pattern for many views, it should be fairly easy to create a mixin that does the push+register+pop, something like:
```dart
class LocalControllerMixin<T> on State {
  
  T get controller; // each view must implement this

  void initState(){
    getIt.pushScope();
    getIt.registerSingleton<T>(getController);
  }
  void dispose(){
    getIt.popScope();
  }
}
```
Then a view would just need something like:
```dart
MyViewState extends State with LocalControllerMixin<Bar> {
   Bar get controller => Bar();
}
```

Overall it feels like GetIt is overkill for this use case though, if you just need per-view controllers, there are easier ways. 

One approach is to just use a StatefulWidget as your "view model", and a child stateless widget for the view. You pass the state into the child, so it can call various actions or react to the current state:
https://blog.gskinner.com/archives/2020/02/flutter-widgetview-a-simple-separation-of-layout-and-logic.html

Anytime the model changes it can just call `setState` to re-render. It gives a nice separation of Controller / View, you can use `dispose` method to do cleanup. No real need for external libraries in this case, imo.

Basic structure in code:
```dart
class MyWidget extends StatefulWidget {
  @override
  _MyWidgetController createState() => _MyWidgetController();
}
 
/// This state acts as your 'ViewModel'
class _MyWidgetController extends State<MyWidget> {
  @override
  Widget build(BuildContext context) => _MyWidgetView(this);
 
  //////////////////////////////////////////////////////////
  // UI event handlers, init code, etc goes here
  //////////////////////////////////////////////////////////
 
  void doStuff(){
    // change some state, load some stuff, etc
    setState(); // re-render
  }

}
 
class _MyWidgetView extends WidgetView<MyWidget, _MyWidgetController> {
  _MyWidgetView(_MyWidgetController state) : super(state);
 
  @override
  Widget build(BuildContext context) {
 
    //////////////////////////////////////////////////////////
    // Widget tree goes here.
    //////////////////////////////////////////////////////////
    return TextButton(..., onPressed: state.doStuff());
     
  }
}
```

**Comment by kevlar700** [comment]
Although Riverpod provided for quite nice boiler plate free code. I hear that they may be deprecating changenotifierprovider. Currently immutable statenotifiers are preferred by Riverpods documentation. I think mutable code is much nicer to read and write. Although oblivious to it, most of the time. Riverpod also resulted in some abstraction and complexity.

Thank you @esDotDev and @escamoteur. I believe this approach for local state along with get_it and watch_it for globally accessible changenotifers is the way that I personally shall proceed.

**Comment by escamoteur** [comment]
Thanks a lot for the kind words. I encourage to add flutter_command to get even more control and flexibility 😊
Am 29. Juni 2023, 18:17 +0200 schrieb Kevin Chadwick ***@***.***>:

**Comment by janmiderback** [comment]
Thanks for all comments and suggestions!
My team is still in progress of evaluating different approaches to state management.
Your input is highly appreciated.
