### ISSUE TITLE
Question Regarding Example in Readme

### ISSUE THREAD

**Issue by cliftonlabrum** [escamoteur/get_it_mixin#28]
I have a simple question. The Readme shows this example:
```dart
class UserModel extends ChangeNotifier {
  get name = _name;
  String _name = '';
  set name(String value){
    _name = value;
    notifyListeners();
  }
  ...
}
```
Why create a getter that points to `_name`? Isn't that redundant to just using `name`?

```dart
class UserModel extends ChangeNotifier {
  String name = '';
  set name(String value){
    name = value;
    notifyListeners();
  }
  ...
}
```
Can you help me understand the need for a getter alongside a property? Thanks! 😊

**Comment by esDotDev** [comment]
With the latter example it would be easy for someone to mistakenly set the name field, instead of the accessor. 

Not to mention, it would not compile because you can't re-use the same field name twice.
