### ISSUE TITLE
How to use registerHandler for same subsequent calls ? 

### ISSUE THREAD

**Issue by blackkara** [escamoteur/get_it_mixin#29]
I am trying to use registerHandler to display the gallery permission dialog whenever the user clicks to open the gallery. However, I am having trouble integrating and using it properly. 

The problem is that it only works the first time, and subsequent calls to `isGalleryPermissionDenied.value = true;` do not trigger notifyListeners as expected. I have tried manually calling `isGalleryPermissionDenied.notifyListeners(),` but this causes it to trigger twice initially. 

How can I properly use registerHandler to display dialog if gallery is denied and trigger notifyListeners as expected?

```
class ProfilePhotoScreen extends StatelessWidget with GetItMixin {
  ProfilePhotoScreen({Key? key}) : super(key: key);

  void onGalleryPermissionDenied(context, newValue, cancel) {
    showPermissionDeniedDialogNew(...);
  }
  
  @override
  Widget build(BuildContext context) {
    registerHandler((ProfilePhotoViewModel vm) => vm.isGalleryPermissionDenied, onGalleryPermissionDenied);
    ...
  }
}

class ProfilePhotoViewModel with Disposable {
  ProfilePhotoViewModel({required this.imageService});
  
  ValueNotifier<bool> isGalleryPermissionDenied = ValueNotifier(false);
  
   void pickImage(BuildContext context) {
    ...
    isGalleryPermissionDenied.value = true;
  }
}
```

**Comment by escamoteur** [comment]
The problem is that the default behaviour of ValueNotifiers is that if the value isn't changed, they don't call notifiyListeners.
You can use the CustomValueNotifier of my package functional_listener or check out my flutter_command package :-)

**Comment by blackkara** [comment]
`CustomValueNotifier` from functional_listener solved, thanks. 👍🏻
