### ISSUE TITLE
Possible syntax simplification - type inference

### ISSUE THREAD

**Issue by mdccxv** [escamoteur/get_it_mixin#32]
1. Say I have a Value Notifier, controller and a widget (it's a simplified example)
```dart
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:get_it_mixin/get_it_mixin.dart';

class FirstSampleNotifier extends ValueNotifier<Model?> {
  FirstSampleNotifier() : super(null);
}

class Model {}

class FirstController {
  final FirstSampleNotifier firstSampleNotifier;

  FirstController(this.firstSampleNotifier);
}

class FirstWidget extends StatelessWidget with GetItMixin {
  FirstWidget({super.key});

  final firstController = GetIt.I<FirstController>();

  @override
  Widget build(BuildContext context) {
    final model = watch(target: firstController.firstSampleNotifier);
    return const Scaffold();
  }
}
```
The type of `model` in the build method isn't inferred (it's `dynamic`), unless I do instead:
`final model = watch<ValueNotifier<Model?>, Model?>(target: firstController.firstSampleNotifier);`
then it's correctly identified as being `Model?`.
**Is there something I'm missing or is this long way of putting it the only way when the Value Notifier type is nullable?**

2. Similar example with a value notifier whose value is bool and it isn't nullable:
```dart
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:get_it_mixin/get_it_mixin.dart';

class SecondSampleNotifier extends ValueNotifier<bool> {
  SecondSampleNotifier() : super(false);
}

class SecondController {
  final SecondSampleNotifier secondSampleNotifier;

  SecondController(this.secondSampleNotifier);
}

class SecondWidget extends StatelessWidget with GetItMixin {
  SecondWidget({super.key});

  final secondController = GetIt.I<SecondController>();

  @override
  Widget build(BuildContext context) {
    final boolValue = watch(target: secondController.secondSampleNotifier);
    return const Scaffold();
  }
}
```
Again, the type of `boolValue` isn't inferred, I have to write instead
`final bool boolValue = watch(target: secondController.secondSampleNotifier);`
which isn't a big thing, but am I missing something here? Is there some syntactic sugar I don't see?

**Comment by escamoteur** [comment]
I recommend switching to my new package watch_it which has a more intuitive API and probably solves your problem too.
