### ISSUE TITLE
get watch watchOnly  getX watchX  watchOnlyX  

### ISSUE THREAD

**Issue by formvoltron** [escamoteur/get_it_mixin#7]
After reading the docs about 4 times I cannot for the life of me figure out what the difference between these are.

There are no examples in the example code.

**Comment by formvoltron** [comment]
handlers have 3 forms:  futures, streams, and valueListenables.  

So why do "widget updates on update have so many forms of watch/get/x/only/yada yada yada?

**Comment by formvoltron** [comment]
Now I have read the source code & can see that get & getX & getAsync seem to have nothing to do with re-rendering state.  They seem to only be shortcuts for get_it   Why not just put those in get_it? 

Wait a sec.. now I see that one is getX and another is getx. Is there a reason for that?

**Comment by escamoteur** [comment]
Hi,
I'm sorry if it isn't clear from the docs.

get and getX are use shortcuts that you don't have to write GetIt.I.<Type>
watch and watchX oberverse ValueListenables either that the registered object itself is a ValueListenable (watch) and watchX if a property inside an object registered in getIt is a one.
watchOnly is if your Object inside GetIt implements ChangeNotifier but you only want to rebuild if the value of one of its property has changed. watchXOnly is if you want to do the same but for  a property of the Object in getIt.

**Comment by formvoltron** [comment]
Phew!  OK.  I think I have all that.  Yes the shorthands for get_it did throw me off... You already have so many choices, so why add those ones when they aren't really doing the watching that this package is designed for?

Once reflection in dart is stable (I see that dart:mirrors is marked as unstable), maybe it would make sense to use a code generator to create wrappers around the developer's model api?  This way get_it_mixin could just have one method watcher() which can just add whatever wrapper is required around the model.  The developer can keep his model free from this implementation specific stuff, meanwhile allowing injection of state changes into the widget tree.

whaddyathink?

**Comment by escamoteur** [comment]
we will never get reflection working in Flutter.
